apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
  namespace: weather-namespace  
  labels:
    app: weather-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
      - name: weather-app
        image: sasibk/weather-app:19
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_KEY
          value: "de0ed5aadcmshb4eb1566860eecep1cc1ddjsne00fd7d03e20"


            
